Server:
  SERVER_PORT: 8080
  SERVER_HOST: "127.0.0.1"
  HTTP_VERSION: "HTTP/1.1"

RunTime:
  MAX_CONCURRENT_CONNECTIONS: 100
  ENABLE_PESISTANT: True
  ENABLE_PIPELINING: True
  MAX_PIPELINING_NUMBER: 10